name: shared_repo
description: Dart package shared repo.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0


environment:
  sdk: '>=2.17.0 <3.0.0'

#dependencies:

dev_dependencies:
  flutter_lints: ^2.0.1
  lints: ^2.0.0