import 'package:shared_repo/models/Items.dart';

class AlbumsResponse {
  AlbumsResponse({
    required this.next,
    required this.total,
    required this.offset,
    required this.limit,
    required this.href,
    required this.items,
  });

  String next;
  int total;
  int offset;
  int limit;
  String href;
  List<AlbumItems> items;

  factory AlbumsResponse.fromJson(Map<dynamic, dynamic> json) => AlbumsResponse(
    next: json["next"],
    total: json["total"],
    offset: json["offset"],
    limit: json["limit"],
    href: json["href"],
    items: List<AlbumItems>.from(json["items"].map((x) => AlbumItems.fromJson(x))),
  );

  Map<dynamic, dynamic> toJson() => {
    "next": next,
    "total": total,
        "offset": offset,
        "limit": limit,
        "href": href,
        "items": List<dynamic>.from(items.map((x) => x.toJson())),
      };

  @override
  String toString() {
    return 'AlbumsResponse{next: $next, total: $total, offset: $offset, limit: $limit, href: $href, items: $items}';
  }

  factory AlbumsResponse.dummy() {
    var json = {
      "href":
      "https://api.spotify.com/v1/browse/new-releases?country=IN&offset=0&limit=5",
      "items": [
        {
          "album_type": "single",
          "artists": [
            {
              "external_urls": {
                "spotify":
                "https://open.spotify.com/artist/1wRPtKGflJrBx9BmLsSwlU"
              },
              "href":
              "https://api.spotify.com/v1/artists/1wRPtKGflJrBx9BmLsSwlU",
              "id": "1wRPtKGflJrBx9BmLsSwlU",
              "name": "Pritam",
              "type": "artist",
              "uri": "spotify:artist:1wRPtKGflJrBx9BmLsSwlU"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/1t1gWslYejaaqicumEbdKU"
          },
          "href": "https://api.spotify.com/v1/albums/1t1gWslYejaaqicumEbdKU",
          "id": "1t1gWslYejaaqicumEbdKU",
          "images": [
            {
              "height": 640,
              "url":
              "https://i.scdn.co/image/ab67616d0000b27360098f31391483986de30b66",
              "width": 640
            },
            {
              "height": 300,
              "url":
              "https://i.scdn.co/image/ab67616d00001e0260098f31391483986de30b66",
              "width": 300
            },
            {
              "height": 64,
              "url":
              "https://i.scdn.co/image/ab67616d0000485160098f31391483986de30b66",
              "width": 64
            }
          ],
          "name": "Tu Jhoothi Main Makkaar",
          "release_date": "2023-03-16",
          "release_date_precision": "day",
          "total_tracks": 6,
          "type": "album",
          "uri": "spotify:album:1t1gWslYejaaqicumEbdKU"
        },
        {
          "album_type": "single",
          "artists": [
            {
              "external_urls": {
                "spotify":
                "https://open.spotify.com/artist/50iBEPSw6kQ8GQkumXz7XZ"
              },
              "href":
              "https://api.spotify.com/v1/artists/50iBEPSw6kQ8GQkumXz7XZ",
              "id": "50iBEPSw6kQ8GQkumXz7XZ",
              "name": "Hesham Abdul Wahab",
              "type": "artist",
              "uri": "spotify:artist:50iBEPSw6kQ8GQkumXz7XZ"
            },
            {
              "external_urls": {
                "spotify":
                "https://open.spotify.com/artist/1gajAFPKcgGySskFCZ7qQD"
              },
              "href":
              "https://api.spotify.com/v1/artists/1gajAFPKcgGySskFCZ7qQD",
              "id": "1gajAFPKcgGySskFCZ7qQD",
              "name": "Shiva Nirvana",
              "type": "artist",
              "uri": "spotify:artist:1gajAFPKcgGySskFCZ7qQD"
            }
          ],
          "available_markets": ["IN"],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/2rYw1yEuTj2qOHj3J8YTJN"
          },
          "href": "https://api.spotify.com/v1/albums/2rYw1yEuTj2qOHj3J8YTJN",
          "id": "2rYw1yEuTj2qOHj3J8YTJN",
          "images": [
            {
              "height": 640,
              "url":
              "https://i.scdn.co/image/ab67616d0000b27354f142b48177e144dc6d525a",
              "width": 640
            },
            {
              "height": 300,
              "url":
              "https://i.scdn.co/image/ab67616d00001e0254f142b48177e144dc6d525a",
              "width": 300
            },
            {
              "height": 64,
              "url":
              "https://i.scdn.co/image/ab67616d0000485154f142b48177e144dc6d525a",
              "width": 64
            }
          ],
          "name": "Na Roja Nuvve (From \"Kushi\") (Telugu)",
          "release_date": "2023-05-09",
          "release_date_precision": "day",
          "total_tracks": 1,
          "type": "album",
          "uri": "spotify:album:2rYw1yEuTj2qOHj3J8YTJN"
        },
        {
          "album_type": "single",
          "artists": [
            {
              "external_urls": {
                "spotify":
                "https://open.spotify.com/artist/3PjvC3vaZ6wh5FK6PZ4Dd5"
              },
              "href":
              "https://api.spotify.com/v1/artists/3PjvC3vaZ6wh5FK6PZ4Dd5",
              "id": "3PjvC3vaZ6wh5FK6PZ4Dd5",
              "name": "B. Ajaneesh Loknath",
              "type": "artist",
              "uri": "spotify:artist:3PjvC3vaZ6wh5FK6PZ4Dd5"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/7vQjNbwpLh0RNmFihCMiVa"
          },
          "href": "https://api.spotify.com/v1/albums/7vQjNbwpLh0RNmFihCMiVa",
          "id": "7vQjNbwpLh0RNmFihCMiVa",
          "images": [
            {
              "height": 640,
              "url":
              "https://i.scdn.co/image/ab67616d0000b273b9bd52d483fd372dda233b10",
              "width": 640
            },
            {
              "height": 300,
              "url":
              "https://i.scdn.co/image/ab67616d00001e02b9bd52d483fd372dda233b10",
              "width": 300
            },
            {
              "height": 64,
              "url":
              "https://i.scdn.co/image/ab67616d00004851b9bd52d483fd372dda233b10",
              "width": 64
            }
          ],
          "name": "Virupaksha (Original Motion Picture Soundtrack)",
          "release_date": "2023-04-22",
          "release_date_precision": "day",
          "total_tracks": 3,
          "type": "album",
          "uri": "spotify:album:7vQjNbwpLh0RNmFihCMiVa"
        },
        {
          "album_type": "single",
          "artists": [
            {
              "external_urls": {
                "spotify":
                "https://open.spotify.com/artist/09UmIX92EUH9hAK4bxvHx6"
              },
              "href":
              "https://api.spotify.com/v1/artists/09UmIX92EUH9hAK4bxvHx6",
              "id": "09UmIX92EUH9hAK4bxvHx6",
              "name": "Mithoon",
              "type": "artist",
              "uri": "spotify:artist:09UmIX92EUH9hAK4bxvHx6"
            },
            {
              "external_urls": {
                "spotify":
                "https://open.spotify.com/artist/4IKVDbCSBTxBeAsMKjAuTs"
              },
              "href":
              "https://api.spotify.com/v1/artists/4IKVDbCSBTxBeAsMKjAuTs",
              "id": "4IKVDbCSBTxBeAsMKjAuTs",
              "name": "Armaan Malik",
              "type": "artist",
              "uri": "spotify:artist:4IKVDbCSBTxBeAsMKjAuTs"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/7jCaWezpvGA2Ktjsq4GNwX"
          },
          "href": "https://api.spotify.com/v1/albums/7jCaWezpvGA2Ktjsq4GNwX",
          "id": "7jCaWezpvGA2Ktjsq4GNwX",
          "images": [
            {
              "height": 640,
              "url":
              "https://i.scdn.co/image/ab67616d0000b273bfe67709866965195d309782",
              "width": 640
            },
            {
              "height": 300,
              "url":
              "https://i.scdn.co/image/ab67616d00001e02bfe67709866965195d309782",
              "width": 300
            },
            {
              "height": 64,
              "url":
              "https://i.scdn.co/image/ab67616d00004851bfe67709866965195d309782",
              "width": 64
            }
          ],
          "name": "Wahi Toh Khuda Hai",
          "release_date": "2023-04-27",
          "release_date_precision": "day",
          "total_tracks": 1,
          "type": "album",
          "uri": "spotify:album:7jCaWezpvGA2Ktjsq4GNwX"
        },
        {
          "album_type": "single",
          "artists": [
            {
              "external_urls": {
                "spotify":
                "https://open.spotify.com/artist/5UdFr0GeO7jKIaNIJgwB36"
              },
              "href":
              "https://api.spotify.com/v1/artists/5UdFr0GeO7jKIaNIJgwB36",
              "id": "5UdFr0GeO7jKIaNIJgwB36",
              "name": "Raftaar",
              "type": "artist",
              "uri": "spotify:artist:5UdFr0GeO7jKIaNIJgwB36"
            },
            {
              "external_urls": {
                "spotify":
                "https://open.spotify.com/artist/4mRPyvdSBxARQIFeXXM13s"
              },
              "href":
              "https://api.spotify.com/v1/artists/4mRPyvdSBxARQIFeXXM13s",
              "id": "4mRPyvdSBxARQIFeXXM13s",
              "name": "AKASA",
              "type": "artist",
              "uri": "spotify:artist:4mRPyvdSBxARQIFeXXM13s"
            }
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/0Y3n8uUIxd9dzXLqrJOGnh"
          },
          "href": "https://api.spotify.com/v1/albums/0Y3n8uUIxd9dzXLqrJOGnh",
          "id": "0Y3n8uUIxd9dzXLqrJOGnh",
          "images": [
            {
              "height": 640,
              "url":
              "https://i.scdn.co/image/ab67616d0000b273e01db9d23e1ff625e3b288b9",
              "width": 640
            },
            {
              "height": 300,
              "url":
              "https://i.scdn.co/image/ab67616d00001e02e01db9d23e1ff625e3b288b9",
              "width": 300
            },
            {
              "height": 64,
              "url":
              "https://i.scdn.co/image/ab67616d00004851e01db9d23e1ff625e3b288b9",
              "width": 64
            }
          ],
          "name": "Phone Mila Ke (feat. Aroosa Khan)",
          "release_date": "2023-04-26",
          "release_date_precision": "day",
          "total_tracks": 1,
          "type": "album",
          "uri": "spotify:album:0Y3n8uUIxd9dzXLqrJOGnh"
        }
      ],
      "limit": 5,
      "next":
      "https://api.spotify.com/v1/browse/new-releases?country=IN&offset=5&limit=5",
      "offset": 0,
      "previous": null,
      "total": 100
    };
    return AlbumsResponse.fromJson(json);
  }
}